"""UrologV3.3 Initial Unified Architecture

Revision ID: 49f17e055bad
Revises: 
Create Date: 2026-03-24 17:50:51.198906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49f17e055bad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anestezi_personelleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anestezi_personelleri_ad'), 'anestezi_personelleri', ['ad'], unique=False)
    op.create_index(op.f('ix_anestezi_personelleri_id'), 'anestezi_personelleri', ['id'], unique=False)
    op.create_table('anestezi_tipleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anestezi_tipleri_ad'), 'anestezi_tipleri', ['ad'], unique=False)
    op.create_index(op.f('ix_anestezi_tipleri_id'), 'anestezi_tipleri', ['id'], unique=False)
    op.create_table('asistanlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistanlar_ad'), 'asistanlar', ['ad'], unique=False)
    op.create_index(op.f('ix_asistanlar_id'), 'asistanlar', ['id'], unique=False)
    op.create_table('biyopsi_sablonlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('lokasyon', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biyopsi_sablonlari_id'), 'biyopsi_sablonlari', ['id'], unique=False)
    op.create_table('cerrahlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cerrahlar_ad'), 'cerrahlar', ['ad'], unique=False)
    op.create_index(op.f('ix_cerrahlar_id'), 'cerrahlar', ['id'], unique=False)
    op.create_table('doktorlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(), nullable=False),
    sa.Column('brans', sa.String(), nullable=True),
    sa.Column('diploma_no', sa.String(), nullable=True),
    sa.Column('tescil_no', sa.String(), nullable=True),
    sa.Column('uzmanlik_tescil_no', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doktorlar_ad_soyad'), 'doktorlar', ['ad_soyad'], unique=False)
    op.create_index(op.f('ix_doktorlar_id'), 'doktorlar', ['id'], unique=False)
    op.create_table('durum_bildirir_raporlari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('tani_bulgular', sa.Text(), nullable=True),
    sa.Column('icd_kodu', sa.String(length=50), nullable=True),
    sa.Column('sonuc_kanaat', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_durum_bildirir_raporlari_hasta_id'), 'durum_bildirir_raporlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_durum_bildirir_raporlari_id'), 'durum_bildirir_raporlari', ['id'], unique=False)
    op.create_table('ekip_uyeleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_soyad', sa.String(), nullable=False),
    sa.Column('gorev', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ekip_uyeleri_id'), 'ekip_uyeleri', ['id'], unique=False)
    op.create_table('finans_hizmetler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=True),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('varsayilan_fiyat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finans_hizmetler_id'), 'finans_hizmetler', ['id'], unique=False)
    op.create_table('finans_kategoriler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('ust_kategori_id', sa.Integer(), nullable=True),
    sa.Column('renk', sa.String(length=7), nullable=True),
    sa.Column('ikon', sa.String(length=50), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ust_kategori_id'], ['finans_kategoriler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finans_kategoriler_id'), 'finans_kategoriler', ['id'], unique=False)
    op.create_table('firmalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('vergi_dairesi', sa.String(length=100), nullable=True),
    sa.Column('vergi_no', sa.String(length=20), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('yetkili', sa.String(length=100), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmalar_id'), 'firmalar', ['id'], unique=False)
    op.create_table('fotograflar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('asama', sa.String(length=50), nullable=True),
    sa.Column('etiketler', sa.String(length=255), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=255), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotograflar_hasta_id'), 'fotograflar', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_fotograflar_id'), 'fotograflar', ['id'], unique=False)
    op.create_table('hastalar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tc_kimlik', sa.String(length=11), nullable=True),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('cinsiyet', sa.String(length=10), nullable=True),
    sa.Column('cep_tel', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('dogum_yeri', sa.String(length=100), nullable=True),
    sa.Column('kan_grubu', sa.String(length=10), nullable=True),
    sa.Column('medeni_hal', sa.String(length=20), nullable=True),
    sa.Column('meslek', sa.String(length=100), nullable=True),
    sa.Column('doktor', sa.String(length=100), nullable=True),
    sa.Column('kimlik_notlar', sa.Text(), nullable=True),
    sa.Column('protokol_no', sa.String(length=50), nullable=True),
    sa.Column('ev_tel', sa.String(length=20), nullable=True),
    sa.Column('is_tel', sa.String(length=20), nullable=True),
    sa.Column('referans', sa.String(length=100), nullable=True),
    sa.Column('postakodu', sa.String(length=10), nullable=True),
    sa.Column('kurum', sa.String(length=100), nullable=True),
    sa.Column('sigorta', sa.String(length=100), nullable=True),
    sa.Column('ozelsigorta', sa.String(length=100), nullable=True),
    sa.Column('cocuk_sayisi', sa.Integer(), nullable=True),
    sa.Column('sms_izin', sa.Boolean(), nullable=True),
    sa.Column('email_izin', sa.Boolean(), nullable=True),
    sa.Column('iletisim_kaynagi', sa.String(length=50), nullable=True),
    sa.Column('iletisim_tercihi', sa.String(length=50), nullable=True),
    sa.Column('kayit_notu', sa.Text(), nullable=True),
    sa.Column('arama_izni', sa.String(length=10), nullable=True),
    sa.Column('iletisim_yakini_iliski', sa.String(length=50), nullable=True),
    sa.Column('iletisim_yakini_tel', sa.String(length=20), nullable=True),
    sa.Column('iletisim_kisi', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Emergency/alt contact persons [{yakinlik, isim, telefon}]'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hastalar_ad'), 'hastalar', ['ad'], unique=False)
    op.create_index(op.f('ix_hastalar_id'), 'hastalar', ['id'], unique=False)
    op.create_index(op.f('ix_hastalar_protokol_no'), 'hastalar', ['protokol_no'], unique=False)
    op.create_index(op.f('ix_hastalar_soyad'), 'hastalar', ['soyad'], unique=False)
    op.create_index(op.f('ix_hastalar_tc_kimlik'), 'hastalar', ['tc_kimlik'], unique=True)
    op.create_table('hastaneler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hastaneler_ad'), 'hastaneler', ['ad'], unique=False)
    op.create_index(op.f('ix_hastaneler_id'), 'hastaneler', ['id'], unique=False)
    op.create_table('hemsireler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hemsireler_ad'), 'hemsireler', ['ad'], unique=False)
    op.create_index(op.f('ix_hemsireler_id'), 'hemsireler', ['id'], unique=False)
    op.create_table('icd_tanilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kodu', sa.String(), nullable=False),
    sa.Column('adi', sa.String(), nullable=True),
    sa.Column('ust_kodu', sa.String(), nullable=True),
    sa.Column('aktif', sa.String(), nullable=True),
    sa.Column('seviye', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icd_tanilar_adi'), 'icd_tanilar', ['adi'], unique=False)
    op.create_index(op.f('ix_icd_tanilar_id'), 'icd_tanilar', ['id'], unique=False)
    op.create_index(op.f('ix_icd_tanilar_kodu'), 'icd_tanilar', ['kodu'], unique=True)
    op.create_table('ilac_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('etkin_madde', sa.String(), nullable=True),
    sa.Column('atc_kodu', sa.String(), nullable=True),
    sa.Column('fiyat', sa.String(), nullable=True),
    sa.Column('firma', sa.String(), nullable=True),
    sa.Column('recete_tipi', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ilac_tanimlari_barcode'), 'ilac_tanimlari', ['barcode'], unique=False)
    op.create_index(op.f('ix_ilac_tanimlari_id'), 'ilac_tanimlari', ['id'], unique=False)
    op.create_index(op.f('ix_ilac_tanimlari_name'), 'ilac_tanimlari', ['name'], unique=False)
    op.create_table('istirahat_raporlari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('baslangic_tarihi', sa.DateTime(), nullable=True),
    sa.Column('bitis_tarihi', sa.DateTime(), nullable=True),
    sa.Column('icd_kodu', sa.String(length=50), nullable=True),
    sa.Column('tani', sa.Text(), nullable=True),
    sa.Column('karar', sa.String(length=100), nullable=True),
    sa.Column('kontrol_tarihi', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_istirahat_raporlari_hasta_id'), 'istirahat_raporlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_istirahat_raporlari_id'), 'istirahat_raporlari', ['id'], unique=False)
    op.create_table('kasalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('tip', sa.String(length=20), nullable=False),
    sa.Column('bakiye', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('banka_adi', sa.String(length=100), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('sira_no', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kasalar_id'), 'kasalar', ['id'], unique=False)
    op.create_table('konsultasyon_raporlari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('hitap_klinisyen', sa.String(length=255), nullable=True),
    sa.Column('ozgecmis', sa.Text(), nullable=True),
    sa.Column('tani', sa.Text(), nullable=True),
    sa.Column('ilaclar', sa.Text(), nullable=True),
    sa.Column('sikayet', sa.Text(), nullable=True),
    sa.Column('oyku', sa.Text(), nullable=True),
    sa.Column('talep', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(length=255), nullable=True),
    sa.Column('rapor_metni', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_konsultasyon_raporlari_hasta_id'), 'konsultasyon_raporlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_konsultasyon_raporlari_id'), 'konsultasyon_raporlari', ['id'], unique=False)
    op.create_table('kurumlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kurumlar_ad'), 'kurumlar', ['ad'], unique=False)
    op.create_index(op.f('ix_kurumlar_id'), 'kurumlar', ['id'], unique=False)
    op.create_table('meslekler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meslekler_ad'), 'meslekler', ['ad'], unique=False)
    op.create_index(op.f('ix_meslekler_id'), 'meslekler', ['id'], unique=False)
    op.create_table('muayeneler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=False),
    sa.Column('sikayet', sa.Text(), nullable=True),
    sa.Column('oyku', sa.Text(), nullable=True),
    sa.Column('bulgu_notu', sa.Text(), nullable=True),
    sa.Column('tani1', sa.String(length=255), nullable=True),
    sa.Column('tani_kesin', sa.Text(), nullable=True),
    sa.Column('tedavi', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(length=100), nullable=True),
    sa.Column('recete', sa.Text(), nullable=True),
    sa.Column('ozgecmis', sa.Text(), nullable=True),
    sa.Column('soygecmis', sa.Text(), nullable=True),
    sa.Column('kullandigi_ilaclar', sa.Text(), nullable=True),
    sa.Column('kan_sulandirici', sa.Integer(), nullable=True),
    sa.Column('aliskanliklar', sa.Text(), nullable=True),
    sa.Column('sistem_sorgu', sa.Text(), nullable=True),
    sa.Column('ipss_skor', sa.String(length=50), nullable=True),
    sa.Column('iief_ef_skor', sa.String(length=50), nullable=True),
    sa.Column('iief_ef_answers', sa.Text(), nullable=True),
    sa.Column('fizik_muayene', sa.Text(), nullable=True),
    sa.Column('erektil_islev', sa.String(length=50), nullable=True),
    sa.Column('ejakulasyon', sa.String(length=50), nullable=True),
    sa.Column('mshq', sa.String(length=50), nullable=True),
    sa.Column('prosedur', sa.Text(), nullable=True),
    sa.Column('allerjiler', sa.Text(), nullable=True),
    sa.Column('tani1_kodu', sa.String(length=50), nullable=True),
    sa.Column('tani2', sa.String(length=255), nullable=True),
    sa.Column('tani2_kodu', sa.String(length=50), nullable=True),
    sa.Column('tani3', sa.String(length=255), nullable=True),
    sa.Column('tani3_kodu', sa.String(length=50), nullable=True),
    sa.Column('tani4', sa.String(length=255), nullable=True),
    sa.Column('tani4_kodu', sa.String(length=50), nullable=True),
    sa.Column('tani5', sa.String(length=255), nullable=True),
    sa.Column('tani5_kodu', sa.String(length=50), nullable=True),
    sa.Column('oneriler', sa.Text(), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('tansiyon', sa.String(length=50), nullable=True),
    sa.Column('ates', sa.String(length=50), nullable=True),
    sa.Column('kvah', sa.String(length=50), nullable=True),
    sa.Column('bobrek_sag', sa.String(length=50), nullable=True),
    sa.Column('bobrek_sol', sa.String(length=50), nullable=True),
    sa.Column('suprapubik_kitle', sa.String(length=50), nullable=True),
    sa.Column('ego', sa.String(length=50), nullable=True),
    sa.Column('rektal_tuse', sa.Text(), nullable=True),
    sa.Column('disuri', sa.String(length=10), nullable=True),
    sa.Column('pollakiuri', sa.String(length=10), nullable=True),
    sa.Column('nokturi', sa.String(length=10), nullable=True),
    sa.Column('hematuri', sa.String(length=10), nullable=True),
    sa.Column('genital_akinti', sa.String(length=10), nullable=True),
    sa.Column('kabizlik', sa.String(length=10), nullable=True),
    sa.Column('tas_oyku', sa.String(length=10), nullable=True),
    sa.Column('catallanma', sa.String(length=10), nullable=True),
    sa.Column('projeksiyon_azalma', sa.String(length=10), nullable=True),
    sa.Column('kalibre_incelme', sa.String(length=10), nullable=True),
    sa.Column('idrar_bas_zorluk', sa.String(length=10), nullable=True),
    sa.Column('kesik_idrar_yapma', sa.String(length=10), nullable=True),
    sa.Column('terminal_damlama', sa.String(length=10), nullable=True),
    sa.Column('residiv_hissi', sa.String(length=10), nullable=True),
    sa.Column('inkontinans', sa.String(length=10), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muayeneler_hasta_id'), 'muayeneler', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_muayeneler_id'), 'muayeneler', ['id'], unique=False)
    op.create_table('notlar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('tip', sa.String(length=100), nullable=True),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('sembol', sa.String(length=50), nullable=True),
    sa.Column('etiketler', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notlar_hasta_id'), 'notlar', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_notlar_id'), 'notlar', ['id'], unique=False)
    op.create_table('operasyonlar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('ameliyat', sa.String(length=255), nullable=True),
    sa.Column('pre_op_tani', sa.String(length=255), nullable=True),
    sa.Column('post_op_tani', sa.String(length=255), nullable=True),
    sa.Column('ekip', sa.Text(), nullable=True),
    sa.Column('hemsire', sa.String(length=100), nullable=True),
    sa.Column('anestezi_ekip', sa.String(length=100), nullable=True),
    sa.Column('anestezi_tur', sa.String(length=50), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('patoloji', sa.Text(), nullable=True),
    sa.Column('post_op', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('hastane_id', sa.String(length=50), nullable=True),
    sa.Column('asa_skoru', sa.String(length=50), nullable=True),
    sa.Column('anestezi_sekli', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operasyonlar_hasta_id'), 'operasyonlar', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_operasyonlar_id'), 'operasyonlar', ['id'], unique=False)
    op.create_table('ozel_sigortalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ozel_sigortalar_ad'), 'ozel_sigortalar', ['ad'], unique=False)
    op.create_index(op.f('ix_ozel_sigortalar_id'), 'ozel_sigortalar', ['id'], unique=False)
    op.create_table('randevu_turleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('sure', sa.Integer(), nullable=True),
    sa.Column('renk', sa.String(length=7), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_randevu_turleri_ad'), 'randevu_turleri', ['ad'], unique=False)
    op.create_index(op.f('ix_randevu_turleri_id'), 'randevu_turleri', ['id'], unique=False)
    op.create_table('recete_sablonlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('icerik', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recete_sablonlari_ad'), 'recete_sablonlari', ['ad'], unique=False)
    op.create_index(op.f('ix_recete_sablonlari_id'), 'recete_sablonlari', ['id'], unique=False)
    op.create_table('sablon_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grup', sa.String(), nullable=False),
    sa.Column('kod', sa.String(), nullable=True),
    sa.Column('icerik', sa.String(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sablon_tanimlari_grup'), 'sablon_tanimlari', ['grup'], unique=False)
    op.create_index(op.f('ix_sablon_tanimlari_id'), 'sablon_tanimlari', ['id'], unique=False)
    op.create_index(op.f('ix_sablon_tanimlari_kod'), 'sablon_tanimlari', ['kod'], unique=False)
    op.create_table('stok_urunler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urun_adi', sa.String(length=255), nullable=False),
    sa.Column('marka', sa.String(length=100), nullable=True),
    sa.Column('urun_tipi', sa.String(length=50), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('birim_fiyat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mevcut_stok', sa.Integer(), nullable=True),
    sa.Column('min_stok', sa.Integer(), nullable=True),
    sa.Column('barkod', sa.String(length=50), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_urunler_barkod'), 'stok_urunler', ['barkod'], unique=False)
    op.create_index(op.f('ix_stok_urunler_id'), 'stok_urunler', ['id'], unique=False)
    op.create_index(op.f('ix_stok_urunler_marka'), 'stok_urunler', ['marka'], unique=False)
    op.create_index(op.f('ix_stok_urunler_urun_adi'), 'stok_urunler', ['urun_adi'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_table('takip_konulari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_takip_konulari_ad'), 'takip_konulari', ['ad'], unique=False)
    op.create_index(op.f('ix_takip_konulari_id'), 'takip_konulari', ['id'], unique=False)
    op.create_table('telefon_gorusmeleri',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telefon_gorusmeleri_hasta_id'), 'telefon_gorusmeleri', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_telefon_gorusmeleri_id'), 'telefon_gorusmeleri', ['id'], unique=False)
    op.create_table('tetkik_tanimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=False),
    sa.Column('grup', sa.String(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tetkik_tanimlari_ad'), 'tetkik_tanimlari', ['ad'], unique=False)
    op.create_index(op.f('ix_tetkik_tanimlari_grup'), 'tetkik_tanimlari', ['grup'], unique=False)
    op.create_index(op.f('ix_tetkik_tanimlari_id'), 'tetkik_tanimlari', ['id'], unique=False)
    op.create_table('tetkikler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('tetkik_adi', sa.String(length=255), nullable=True),
    sa.Column('sonuc', sa.Text(), nullable=True),
    sa.Column('birim', sa.String(length=50), nullable=True),
    sa.Column('referans_araligi', sa.String(length=100), nullable=True),
    sa.Column('sembol', sa.String(length=50), nullable=True),
    sa.Column('dosya_yolu', sa.String(length=255), nullable=True),
    sa.Column('dosya_adi', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tetkikler_hasta_id'), 'tetkikler', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_tetkikler_id'), 'tetkikler', ['id'], unique=False)
    op.create_table('tibbi_mudahale_raporlari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('islem_basligi', sa.String(length=255), nullable=True),
    sa.Column('islem_detayi', sa.Text(), nullable=True),
    sa.Column('sonuc_oneriler', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tibbi_mudahale_raporlari_hasta_id'), 'tibbi_mudahale_raporlari', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_tibbi_mudahale_raporlari_id'), 'tibbi_mudahale_raporlari', ['id'], unique=False)
    op.create_table('trus_biyopsileri',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('psa_total', sa.String(length=50), nullable=True),
    sa.Column('rektal_tuse', sa.Text(), nullable=True),
    sa.Column('mri_var', sa.Boolean(), nullable=True),
    sa.Column('mri_tarih', sa.DateTime(), nullable=True),
    sa.Column('mri_ozet', sa.Text(), nullable=True),
    sa.Column('pirads_lezyon_boyut', sa.String(length=100), nullable=True),
    sa.Column('pirads_lezyon_lokasyon', sa.String(length=100), nullable=True),
    sa.Column('lokasyonlar', sa.Text(), nullable=True),
    sa.Column('prosedur_notu', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trus_biyopsileri_hasta_id'), 'trus_biyopsileri', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_trus_biyopsileri_id'), 'trus_biyopsileri', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('clinic_id', sa.String(length=50), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('skip_audit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clinic_id'), 'users', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('finans_islemler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referans_kodu', sa.String(length=20), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('muayene_id', sa.UUID(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('islem_tipi', sa.String(length=20), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('para_birimi', sa.String(length=3), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('doktor', sa.String(length=100), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('kasa_id', sa.Integer(), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.Column('belge_url', sa.String(length=255), nullable=True),
    sa.Column('iptal_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('iptal_nedeni', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firmalar.id'], ),
    sa.ForeignKeyConstraint(['kasa_id'], ['kasalar.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['finans_kategoriler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finans_islemler_hasta_id'), 'finans_islemler', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_finans_islemler_id'), 'finans_islemler', ['id'], unique=False)
    op.create_index(op.f('ix_finans_islemler_muayene_id'), 'finans_islemler', ['muayene_id'], unique=False)
    op.create_index(op.f('ix_finans_islemler_referans_kodu'), 'finans_islemler', ['referans_kodu'], unique=True)
    op.create_table('kasa_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kasa_id', sa.Integer(), nullable=False),
    sa.Column('hareket_tipi', sa.String(length=20), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('onceki_bakiye', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sonraki_bakiye', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('islem_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kasa_id'], ['kasalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kasa_hareketleri_id'), 'kasa_hareketleri', ['id'], unique=False)
    op.create_table('randevular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('doctor_name', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(), nullable=True),
    sa.Column('google_calendar_id', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_randevular_google_event_id'), 'randevular', ['google_event_id'], unique=False)
    op.create_index(op.f('ix_randevular_hasta_id'), 'randevular', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_randevular_id'), 'randevular', ['id'], unique=False)
    op.create_index(op.f('ix_randevular_is_deleted'), 'randevular', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_randevular_start'), 'randevular', ['start'], unique=False)
    op.create_index(op.f('ix_randevular_status'), 'randevular', ['status'], unique=False)
    op.create_table('sharded_clinical_dosyalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('dosya_tipi', sa.String(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('etiketler', sa.String(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('dosya_adi', sa.String(), nullable=True),
    sa.Column('dosya_yolu', sa.String(), nullable=True),
    sa.Column('legacy_data', sa.LargeBinary(), nullable=True),
    sa.Column('kaynak', sa.String(), nullable=True),
    sa.Column('arsiv_no', sa.String(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharded_clinical_dosyalar_id'), 'sharded_clinical_dosyalar', ['id'], unique=False)
    op.create_table('stok_alimlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('alim_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('miktar', sa.Integer(), nullable=False),
    sa.Column('birim_fiyat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('toplam_tutar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fatura_no', sa.String(length=50), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['firmalar.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['stok_urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_alimlari_id'), 'stok_alimlari', ['id'], unique=False)
    op.create_table('stok_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('hareket_tipi', sa.String(), nullable=False),
    sa.Column('miktar', sa.Integer(), nullable=False),
    sa.Column('islem_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kaynak', sa.String(length=50), nullable=True),
    sa.Column('kaynak_ref', sa.String(length=50), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['stok_urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_hareketleri_id'), 'stok_hareketleri', ['id'], unique=False)
    op.create_table('user_oauth',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'provider')
    )
    op.create_table('finans_islem_satirlari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('islem_id', sa.UUID(), nullable=False),
    sa.Column('hizmet_id', sa.Integer(), nullable=True),
    sa.Column('aciklama', sa.String(length=255), nullable=True),
    sa.Column('miktar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('birim_fiyat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kdv_orani', sa.Integer(), nullable=True),
    sa.Column('toplam_tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hizmet_id'], ['finans_hizmetler.id'], ),
    sa.ForeignKeyConstraint(['islem_id'], ['finans_islemler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finans_islem_satirlari_id'), 'finans_islem_satirlari', ['id'], unique=False)
    op.create_index(op.f('ix_finans_islem_satirlari_islem_id'), 'finans_islem_satirlari', ['islem_id'], unique=False)
    op.create_table('finans_odemeler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('islem_id', sa.UUID(), nullable=False),
    sa.Column('kasa_id', sa.Integer(), nullable=True),
    sa.Column('odeme_yontemi', sa.String(length=50), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('odeme_tarihi', sa.Date(), nullable=False),
    sa.Column('taksit_sayisi', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['islem_id'], ['finans_islemler.id'], ),
    sa.ForeignKeyConstraint(['kasa_id'], ['kasalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finans_odemeler_id'), 'finans_odemeler', ['id'], unique=False)
    op.create_index(op.f('ix_finans_odemeler_islem_id'), 'finans_odemeler', ['islem_id'], unique=False)
    op.create_table('finans_taksitler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('odeme_id', sa.UUID(), nullable=False),
    sa.Column('taksit_no', sa.Integer(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vade_tarihi', sa.Date(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['odeme_id'], ['finans_odemeler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finans_taksitler_id'), 'finans_taksitler', ['id'], unique=False)
    op.create_index(op.f('ix_finans_taksitler_odeme_id'), 'finans_taksitler', ['odeme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finans_taksitler_odeme_id'), table_name='finans_taksitler')
    op.drop_index(op.f('ix_finans_taksitler_id'), table_name='finans_taksitler')
    op.drop_table('finans_taksitler')
    op.drop_index(op.f('ix_finans_odemeler_islem_id'), table_name='finans_odemeler')
    op.drop_index(op.f('ix_finans_odemeler_id'), table_name='finans_odemeler')
    op.drop_table('finans_odemeler')
    op.drop_index(op.f('ix_finans_islem_satirlari_islem_id'), table_name='finans_islem_satirlari')
    op.drop_index(op.f('ix_finans_islem_satirlari_id'), table_name='finans_islem_satirlari')
    op.drop_table('finans_islem_satirlari')
    op.drop_table('user_oauth')
    op.drop_index(op.f('ix_stok_hareketleri_id'), table_name='stok_hareketleri')
    op.drop_table('stok_hareketleri')
    op.drop_index(op.f('ix_stok_alimlari_id'), table_name='stok_alimlari')
    op.drop_table('stok_alimlari')
    op.drop_index(op.f('ix_sharded_clinical_dosyalar_id'), table_name='sharded_clinical_dosyalar')
    op.drop_table('sharded_clinical_dosyalar')
    op.drop_index(op.f('ix_randevular_status'), table_name='randevular')
    op.drop_index(op.f('ix_randevular_start'), table_name='randevular')
    op.drop_index(op.f('ix_randevular_is_deleted'), table_name='randevular')
    op.drop_index(op.f('ix_randevular_id'), table_name='randevular')
    op.drop_index(op.f('ix_randevular_hasta_id'), table_name='randevular')
    op.drop_index(op.f('ix_randevular_google_event_id'), table_name='randevular')
    op.drop_table('randevular')
    op.drop_index(op.f('ix_kasa_hareketleri_id'), table_name='kasa_hareketleri')
    op.drop_table('kasa_hareketleri')
    op.drop_index(op.f('ix_finans_islemler_referans_kodu'), table_name='finans_islemler')
    op.drop_index(op.f('ix_finans_islemler_muayene_id'), table_name='finans_islemler')
    op.drop_index(op.f('ix_finans_islemler_id'), table_name='finans_islemler')
    op.drop_index(op.f('ix_finans_islemler_hasta_id'), table_name='finans_islemler')
    op.drop_table('finans_islemler')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clinic_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trus_biyopsileri_id'), table_name='trus_biyopsileri')
    op.drop_index(op.f('ix_trus_biyopsileri_hasta_id'), table_name='trus_biyopsileri')
    op.drop_table('trus_biyopsileri')
    op.drop_index(op.f('ix_tibbi_mudahale_raporlari_id'), table_name='tibbi_mudahale_raporlari')
    op.drop_index(op.f('ix_tibbi_mudahale_raporlari_hasta_id'), table_name='tibbi_mudahale_raporlari')
    op.drop_table('tibbi_mudahale_raporlari')
    op.drop_index(op.f('ix_tetkikler_id'), table_name='tetkikler')
    op.drop_index(op.f('ix_tetkikler_hasta_id'), table_name='tetkikler')
    op.drop_table('tetkikler')
    op.drop_index(op.f('ix_tetkik_tanimlari_id'), table_name='tetkik_tanimlari')
    op.drop_index(op.f('ix_tetkik_tanimlari_grup'), table_name='tetkik_tanimlari')
    op.drop_index(op.f('ix_tetkik_tanimlari_ad'), table_name='tetkik_tanimlari')
    op.drop_table('tetkik_tanimlari')
    op.drop_index(op.f('ix_telefon_gorusmeleri_id'), table_name='telefon_gorusmeleri')
    op.drop_index(op.f('ix_telefon_gorusmeleri_hasta_id'), table_name='telefon_gorusmeleri')
    op.drop_table('telefon_gorusmeleri')
    op.drop_index(op.f('ix_takip_konulari_id'), table_name='takip_konulari')
    op.drop_index(op.f('ix_takip_konulari_ad'), table_name='takip_konulari')
    op.drop_table('takip_konulari')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_stok_urunler_urun_adi'), table_name='stok_urunler')
    op.drop_index(op.f('ix_stok_urunler_marka'), table_name='stok_urunler')
    op.drop_index(op.f('ix_stok_urunler_id'), table_name='stok_urunler')
    op.drop_index(op.f('ix_stok_urunler_barkod'), table_name='stok_urunler')
    op.drop_table('stok_urunler')
    op.drop_index(op.f('ix_sablon_tanimlari_kod'), table_name='sablon_tanimlari')
    op.drop_index(op.f('ix_sablon_tanimlari_id'), table_name='sablon_tanimlari')
    op.drop_index(op.f('ix_sablon_tanimlari_grup'), table_name='sablon_tanimlari')
    op.drop_table('sablon_tanimlari')
    op.drop_index(op.f('ix_recete_sablonlari_id'), table_name='recete_sablonlari')
    op.drop_index(op.f('ix_recete_sablonlari_ad'), table_name='recete_sablonlari')
    op.drop_table('recete_sablonlari')
    op.drop_index(op.f('ix_randevu_turleri_id'), table_name='randevu_turleri')
    op.drop_index(op.f('ix_randevu_turleri_ad'), table_name='randevu_turleri')
    op.drop_table('randevu_turleri')
    op.drop_index(op.f('ix_ozel_sigortalar_id'), table_name='ozel_sigortalar')
    op.drop_index(op.f('ix_ozel_sigortalar_ad'), table_name='ozel_sigortalar')
    op.drop_table('ozel_sigortalar')
    op.drop_index(op.f('ix_operasyonlar_id'), table_name='operasyonlar')
    op.drop_index(op.f('ix_operasyonlar_hasta_id'), table_name='operasyonlar')
    op.drop_table('operasyonlar')
    op.drop_index(op.f('ix_notlar_id'), table_name='notlar')
    op.drop_index(op.f('ix_notlar_hasta_id'), table_name='notlar')
    op.drop_table('notlar')
    op.drop_index(op.f('ix_muayeneler_id'), table_name='muayeneler')
    op.drop_index(op.f('ix_muayeneler_hasta_id'), table_name='muayeneler')
    op.drop_table('muayeneler')
    op.drop_index(op.f('ix_meslekler_id'), table_name='meslekler')
    op.drop_index(op.f('ix_meslekler_ad'), table_name='meslekler')
    op.drop_table('meslekler')
    op.drop_index(op.f('ix_kurumlar_id'), table_name='kurumlar')
    op.drop_index(op.f('ix_kurumlar_ad'), table_name='kurumlar')
    op.drop_table('kurumlar')
    op.drop_index(op.f('ix_konsultasyon_raporlari_id'), table_name='konsultasyon_raporlari')
    op.drop_index(op.f('ix_konsultasyon_raporlari_hasta_id'), table_name='konsultasyon_raporlari')
    op.drop_table('konsultasyon_raporlari')
    op.drop_index(op.f('ix_kasalar_id'), table_name='kasalar')
    op.drop_table('kasalar')
    op.drop_index(op.f('ix_istirahat_raporlari_id'), table_name='istirahat_raporlari')
    op.drop_index(op.f('ix_istirahat_raporlari_hasta_id'), table_name='istirahat_raporlari')
    op.drop_table('istirahat_raporlari')
    op.drop_index(op.f('ix_ilac_tanimlari_name'), table_name='ilac_tanimlari')
    op.drop_index(op.f('ix_ilac_tanimlari_id'), table_name='ilac_tanimlari')
    op.drop_index(op.f('ix_ilac_tanimlari_barcode'), table_name='ilac_tanimlari')
    op.drop_table('ilac_tanimlari')
    op.drop_index(op.f('ix_icd_tanilar_kodu'), table_name='icd_tanilar')
    op.drop_index(op.f('ix_icd_tanilar_id'), table_name='icd_tanilar')
    op.drop_index(op.f('ix_icd_tanilar_adi'), table_name='icd_tanilar')
    op.drop_table('icd_tanilar')
    op.drop_index(op.f('ix_hemsireler_id'), table_name='hemsireler')
    op.drop_index(op.f('ix_hemsireler_ad'), table_name='hemsireler')
    op.drop_table('hemsireler')
    op.drop_index(op.f('ix_hastaneler_id'), table_name='hastaneler')
    op.drop_index(op.f('ix_hastaneler_ad'), table_name='hastaneler')
    op.drop_table('hastaneler')
    op.drop_index(op.f('ix_hastalar_tc_kimlik'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_soyad'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_protokol_no'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_id'), table_name='hastalar')
    op.drop_index(op.f('ix_hastalar_ad'), table_name='hastalar')
    op.drop_table('hastalar')
    op.drop_index(op.f('ix_fotograflar_id'), table_name='fotograflar')
    op.drop_index(op.f('ix_fotograflar_hasta_id'), table_name='fotograflar')
    op.drop_table('fotograflar')
    op.drop_index(op.f('ix_firmalar_id'), table_name='firmalar')
    op.drop_table('firmalar')
    op.drop_index(op.f('ix_finans_kategoriler_id'), table_name='finans_kategoriler')
    op.drop_table('finans_kategoriler')
    op.drop_index(op.f('ix_finans_hizmetler_id'), table_name='finans_hizmetler')
    op.drop_table('finans_hizmetler')
    op.drop_index(op.f('ix_ekip_uyeleri_id'), table_name='ekip_uyeleri')
    op.drop_table('ekip_uyeleri')
    op.drop_index(op.f('ix_durum_bildirir_raporlari_id'), table_name='durum_bildirir_raporlari')
    op.drop_index(op.f('ix_durum_bildirir_raporlari_hasta_id'), table_name='durum_bildirir_raporlari')
    op.drop_table('durum_bildirir_raporlari')
    op.drop_index(op.f('ix_doktorlar_id'), table_name='doktorlar')
    op.drop_index(op.f('ix_doktorlar_ad_soyad'), table_name='doktorlar')
    op.drop_table('doktorlar')
    op.drop_index(op.f('ix_cerrahlar_id'), table_name='cerrahlar')
    op.drop_index(op.f('ix_cerrahlar_ad'), table_name='cerrahlar')
    op.drop_table('cerrahlar')
    op.drop_index(op.f('ix_biyopsi_sablonlari_id'), table_name='biyopsi_sablonlari')
    op.drop_table('biyopsi_sablonlari')
    op.drop_index(op.f('ix_asistanlar_id'), table_name='asistanlar')
    op.drop_index(op.f('ix_asistanlar_ad'), table_name='asistanlar')
    op.drop_table('asistanlar')
    op.drop_index(op.f('ix_anestezi_tipleri_id'), table_name='anestezi_tipleri')
    op.drop_index(op.f('ix_anestezi_tipleri_ad'), table_name='anestezi_tipleri')
    op.drop_table('anestezi_tipleri')
    op.drop_index(op.f('ix_anestezi_personelleri_id'), table_name='anestezi_personelleri')
    op.drop_index(op.f('ix_anestezi_personelleri_ad'), table_name='anestezi_personelleri')
    op.drop_table('anestezi_personelleri')
    # ### end Alembic commands ###
