"""randevu_tarihce

Revision ID: a534bd3385d6
Revises: p002_db_health
Create Date: 2026-06-29 16:08:09.674442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a534bd3385d6'
down_revision: Union[str, None] = 'p002_db_health'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    if 'randevu_tarihce' not in tables:
        op.create_table('randevu_tarihce',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('randevu_id', sa.Integer(), nullable=True),
        sa.Column('hasta_id', sa.UUID(), nullable=True),
        sa.Column('eski_start', sa.DateTime(timezone=True), nullable=True),
        sa.Column('eski_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('islem_tipi', sa.String(), nullable=False),
        sa.Column('eski_title', sa.String(), nullable=True),
        sa.Column('eski_status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['hasta_id'], ['hastalar.id'], ),
        sa.ForeignKeyConstraint(['randevu_id'], ['randevular.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_randevu_tarihce_created_at'), 'randevu_tarihce', ['created_at'], unique=False)
        op.create_index(op.f('ix_randevu_tarihce_hasta_id'), 'randevu_tarihce', ['hasta_id'], unique=False)
        op.create_index(op.f('ix_randevu_tarihce_randevu_id'), 'randevu_tarihce', ['randevu_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_randevu_tarihce_randevu_id'), table_name='randevu_tarihce')
    op.drop_index(op.f('ix_randevu_tarihce_hasta_id'), table_name='randevu_tarihce')
    op.drop_index(op.f('ix_randevu_tarihce_created_at'), table_name='randevu_tarihce')
    op.drop_table('randevu_tarihce')
    # ### end Alembic commands ###
