"""add_kisisel_notlar_table

Revision ID: bb745c49f95b
Revises: d7e4be3de818
Create Date: 2026-04-04 23:51:05.922115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb745c49f95b'
down_revision: Union[str, None] = 'd7e4be3de818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table('kisisel_notlar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hasta_id', sa.UUID(), nullable=True),
    sa.Column('icerik', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kisisel_notlar_hasta_id'), 'kisisel_notlar', ['hasta_id'], unique=False)
    op.create_index(op.f('ix_kisisel_notlar_id'), 'kisisel_notlar', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_kisisel_notlar_id'), table_name='kisisel_notlar')
    op.drop_index(op.f('ix_kisisel_notlar_hasta_id'), table_name='kisisel_notlar')
    op.drop_table('kisisel_notlar')
    # ### end Alembic commands ###
