"""add_has_private_notes_to_hasta

Revision ID: df3ccc115c72
Revises: bb745c49f95b
Create Date: 2026-04-05 17:47:16.644152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3ccc115c72'
down_revision: Union[str, None] = 'bb745c49f95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hastalar', sa.Column('has_private_notes', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hastalar', 'has_private_notes')
    # ### end Alembic commands ###
